version: "2"

networks:
  proxy-tier:
    external:
      name: nginx-proxy
      
services:  
  wordpress:
    restart: always
    image: nginx
    links:
      - db
      - php
    volumes:
      - "./www:/www"
      - "./data/config/sites.conf:/etc/nginx/conf.d/default.conf"
      - "./data/config/nginx.conf:/etc/nginx/nginx.conf"
      - "./data/tools:/tools"
    entrypoint: /tools/entrypoint_wordpress
    networks:
      - proxy-tier    
    command: 'nginx -g "daemon off;"'
  php:
    restart: always
    links:
      - db
    volumes:
      - "./www:/www"
      - "./data/tools:/tools"
      - "./data/dump:/dump"
    entrypoint: /tools/entrypoint_php
  db:
    restart: always
    image: mysql
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./data/tools:/tools"
    entrypoint: /tools/entrypoint_db

