#!/usr/bin/env bash
set -e


echo "Setting permissions for php container..."
/tools/permission_fix
chown -R www-data:www-data /www
echo "Done."

echo "Set WP Config"
cd /www/wordpress
/tools/wp_config.sh
echo "Done."

echo "Execute Command $@"
exec "$@"
